[package]
name = "pakana-core-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
yottadb = "2.1"
stellar-xdr = "25.0"
log = "0.4"
env_logger = "0.11"
chrono = "0.4"
hex = "0.4"
base64 = "0.21"
ed25519-dalek = "2.0"

